# Generated by Django 6.0.5 on 2026-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_phone_otprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video_aparat", "ویدیو آپارات"),
                            ("video_youtube", "ویدیو یوتیوب"),
                            ("video_direct", "ویدیو مستقیم"),
                            ("link", "لینک"),
                        ],
                        max_length=20,
                    ),
                ),
                ("thumbnail", models.URLField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="برای گروه\u200cبندی: ارائه\u200cها، آز.",
                        max_length=100,
                    ),
                ),
                ("is_new", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "منبع داشبورد",
                "verbose_name_plural": "منابع داشبورد",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
