# Generated by Django 6.0.5 on 2026-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_dashboardresource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardresource",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="dashboardresource",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Category for the resource, use it for grouping the resources",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video_aparat", "Aparat Video"),
                    ("video_youtube", "Youtube Video"),
                    ("video_direct", "Direct Video"),
                    ("link", "Link"),
                ],
                max_length=20,
            ),
        ),
    ]
