# Generated by Django 6.0.5 on 2026-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_dashboardresource_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
