"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "your-default-secret-key")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"


ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost").split(",")


ADMIN_URL = os.environ.get("DJANGO_ADMIN_URL", "admin/")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "django_ckeditor_5",
    "storages",
    "django_filters",
]

# Your Apps
INSTALLED_APPS += [
    "accounts", 
    "exams",
    "challenges"
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"
AUTH_USER_MODEL = "accounts.User"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", "sqlite:///db.sqlite3"),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Tehran"
USE_I18N = True
USE_TZ = True


# Reverse Proxy Configuration
# Use FORCE_SCRIPT_NAME only when behind a reverse proxy with a path prefix
# For nginx proxying /api -> backend, set this to '/api' in production
FORCE_SCRIPT_NAME = os.environ.get("DJANGO_FORCE_SCRIPT_NAME", None)

# Use X-Forwarded-Host header
USE_X_FORWARDED_HOST = (
    os.environ.get("DJANGO_USE_X_FORWARDED_HOST", "False").lower() == "true"
)
USE_X_FORWARDED_PORT = (
    os.environ.get("DJANGO_USE_X_FORWARDED_PORT", "False").lower() == "true"
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = FORCE_SCRIPT_NAME + "/static/" if FORCE_SCRIPT_NAME else "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
WHITENOISE_STATIC_PREFIX = "/static/"
MEDIA_URL = FORCE_SCRIPT_NAME + "/media/" if FORCE_SCRIPT_NAME else "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# --- S3 Settings ---
# These are read regardless of DEBUG, but only used by the S3 storage backend
# when DEBUG=False. Safe to leave empty in development.
S3_BUCKET_NAME = os.environ.get("S3_BUCKET_NAME", "")
S3_ACCESS_KEY = os.environ.get("S3_ACCESS_KEY", "")
S3_SECRET_KEY = os.environ.get("S3_SECRET_KEY", "")
S3_ENDPOINT = os.environ.get("S3_ENDPOINT")
if S3_ENDPOINT == "":
    S3_ENDPOINT = None
S3_PRESIGNED_EXPIRE = int(os.environ.get("S3_PRESIGNED_EXPIRE", 300))
MAX_UPLOAD_SIZE_MB = int(os.environ.get("MAX_UPLOAD_SIZE_MB", 10))


# --- Storage Backends ---
# Use S3/MinIO for media files in production, filesystem in development.
if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": S3_ACCESS_KEY,
                "secret_key": S3_SECRET_KEY,
                "bucket_name": S3_BUCKET_NAME,
                "endpoint_url": S3_ENDPOINT,
                "region_name": "us-east-1",
                "addressing_style": "path",
                "signature_version": "s3v4",
                "file_overwrite": False,
                "default_acl": None,
                "querystring_auth": True,
                "querystring_expire": S3_PRESIGNED_EXPIRE,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# --- Cache Configuration ---

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "karsoogh-cache",
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

# Django-ratelimit settings
RATELIMIT_CACHE = "default"
# set in nginx:
# proxy_set_header X-Real-IP $remote_addr;
RATELIMIT_IP_META_KEY = "HTTP_X_REAL_IP"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = (
    os.environ.get("DJANGO_CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"
)
CORS_ALLOW_CREDENTIALS = True

if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]


USER_DAILY_THROTTLE=os.environ.get("USER_DAILY_THROTTLE", 1000)
ANON_DAILY_THROTTLE=os.environ.get("ANON_DAILY_THROTTLE", 300)

# --- Django REST Framework Settings ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": f"{ANON_DAILY_THROTTLE}/day", "user": f"{USER_DAILY_THROTTLE}/day"},
    "DEFAULT_PAGINATION_CLASS": "core.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Karsoogh API",
    "DESCRIPTION": "API for the Karsoogh website.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


ACCESS_TOKEN_LIFETIME_MINUTES = int(os.getenv("ACCESS_TOKEN_LIFETIME_MINUTES", "60"))
REFRESH_TOKEN_LIFETIME_DAYS = int(os.getenv("REFRESH_TOKEN_LIFETIME_DAYS", "7"))
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_TOKEN_LIFETIME_MINUTES),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_TOKEN_LIFETIME_DAYS),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


KAVENEGAR_API_KEY = os.environ.get("KAVENEGAR_API_KEY", "")
KAVENEGAR_OTP_TEMPLATE_NAME = os.environ.get("KAVENEGAR_OTP_TEMPLATE_NAME", "")
KAVENEGAR_TIMEOUT_SECONDS = int(os.environ.get("KAVENEGAR_TIMEOUT_SECONDS", "10"))
OTP_CODE_DIGITS = int(os.environ.get("OTP_CODE_DIGITS", "6"))
OTP_EXPIRY_MINUTES = int(os.environ.get("OTP_EXPIRY_MINUTES", "5"))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get("OTP_RESEND_COOLDOWN_SECONDS", "60"))
OTP_MAX_VERIFY_ATTEMPTS = int(os.environ.get("OTP_MAX_VERIFY_ATTEMPTS", "5"))


# Email Configuration
if DEBUG:
    # In development, print emails to the console
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # In production, use a real SMTP server
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    EMAIL_HOST_USER_FULL = EMAIL_HOST_USER  # Sometimes needed for authentication


DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@karsooghmehregan.ir")
EMAIL_TIMEOUT = 30  # 30 seconds timeout


# --- Security Settings ---
# Use X-Forwarded-Proto header to determine if the request is secure
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security Headers & HTTPS Settings - Environment-based configuration
# In development, disable HTTPS requirements to avoid conflicts with Django dev server
if DEBUG:
    # Development settings - disable HTTPS requirements
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    X_FRAME_OPTIONS = "SAMEORIGIN"
    SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

    # HTTPS Settings - DISABLED for development
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    # Production settings - use environment variables
    SECURE_BROWSER_XSS_FILTER = (
        os.environ.get("DJANGO_SECURE_BROWSER_XSS_FILTER", "True").lower() == "true"
    )
    SECURE_CONTENT_TYPE_NOSNIFF = (
        os.environ.get("DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", "True").lower() == "true"
    )
    X_FRAME_OPTIONS = os.environ.get("DJANGO_X_FRAME_OPTIONS", "DENY")
    SECURE_REFERRER_POLICY = os.environ.get(
        "DJANGO_SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin"
    )

    # HTTPS Settings - ENABLED for production
    SECURE_SSL_REDIRECT = (
        os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true"
    )
    # Exempt the health check endpoint from SSL redirect so the Docker
    # healthcheck (plain HTTP from inside the container) doesn't get 301'd
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower()
        == "true"
    )
    SECURE_HSTS_PRELOAD = (
        os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "True").lower() == "true"
    )
    SESSION_COOKIE_SECURE = (
        os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "True").lower() == "true"
    )
    CSRF_COOKIE_SECURE = (
        os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "True").lower() == "true"
    )

# Logging Configuration
# https://docs.djangoproject.com/en/5.1/topics/logging/
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
    },
}


# --- CKEditor 5 Configuration ---
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|", "bold", "italic", "link", "bulletedList", "numberedList",
            "blockQuote", "imageInsert", "insertTable", "mediaEmbed", "undo", "redo", "sourceEditing"
        ],
        "htmlSupport": {
            "allow": [
                {
                    "name": "/^.*$/",
                    "attributes": True,
                    "classes": True,
                    "styles": True,
                }
            ],
        },
    },
    "extends": {
        "blockToolbar": [
            "paragraph", "heading1", "heading2", "heading3",
            "|", "bulletedList", "numberedList", "|", "blockQuote",
        ],
        "toolbar": [
            "heading", "|", "outdent", "indent", "|", "bold", "italic", "link", "underline", "strikethrough",
            "code", "subscript", "superscript", "highlight", "|", "bulletedList", "numberedList", "todoList",
            "|", "blockQuote", "imageInsert", "insertTable", "mediaEmbed", "fontSize", "fontColor",
            "fontBackgroundColor", "fontFamily", "removeFormat", "sourceEditing"
        ],
        "htmlSupport": {
            "allow": [
                {
                    "name": "/^.*$/",
                    "attributes": True,
                    "classes": True,
                    "styles": True,
                }
            ],
        },
        "image": {
            "toolbar": ["imageTextAlternative", "|", "imageStyle:alignLeft", "imageStyle:alignRight", "imageStyle:side", "fullSize"],
            "upload": {
                "types": ["jpeg", "png", "gif", "bmp", "webp", "tiff"]
            }
        },
        "table": {
            "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells", "tableProperties", "tableCellProperties"],
        },
    }
}

