# Generated by Django 6.0 on 2026-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='question_picture',
            field=models.ImageField(default=1, upload_to='dirQuestions'),
            preserve_default=False,
        ),
    ]
