# Generated by Django 6.0.5 on 2026-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmodel",
            name="max_grade",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
