# Generated by Django 6.0.5 on 2026-07-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_submission_grader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="grader",
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="grader_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="graders",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
