# Generated by Django 6.0.5 on 2026-07-03 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_remove_submission_grader_submission_graded_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="graders",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_staff": True},
                related_name="assigned_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
