# Generated by Django 6.0.5 on 2026-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_submission_graders"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
