# Generated by Django 6.0.5 on 2026-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_submission_graded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
