# Generated by Django 6.0.5 on 2026-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_alter_weeklychallenge_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklychallenge",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
